import "@vibeverse/ui/globals.css";
import { cn } from "@vibeverse/ui/utils";

export const metadata = {
  title: {
    default: "Dashboard",
    template: "Dashboard - %s",
  },
  description: "Generated by create next app",
};

export default function DashLayout({ children }) {
  return (
    <section>
      <header>header admin</header>
      <main>{children}</main>
    </section>
  );
}
